"""Add is_core_staff to Staff

Revision ID: 333188fadcde
Revises: 517a64225f9f
Create Date: 2026-07-07 08:24:01.243602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333188fadcde'
down_revision = '517a64225f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_core_staff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('is_core_staff')

    # ### end Alembic commands ###
