"""Add SiteSettings, Partner, ResourceChapter, OJTAttendance; add is_featured to Project and Publication

Revision ID: 517a64225f9f
Revises: 8ff7773c02fb
Create Date: 2026-07-06 10:31:39.725692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '517a64225f9f'
down_revision = '8ff7773c02fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avp_video_url', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_address', sa.Text(), nullable=True),
    sa.Column('contact_office_hours', sa.String(length=150), nullable=True),
    sa.Column('maps_embed_url', sa.Text(), nullable=True),
    sa.Column('facebook_url', sa.String(length=255), nullable=True),
    sa.Column('youtube_url', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ojt_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ojt_id', sa.Integer(), nullable=False),
    sa.Column('sr_code', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_in', sa.Time(), nullable=True),
    sa.Column('time_out', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ojt_id'], ['ojt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('flipbook_url', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    op.drop_table('resource_chapter')
    op.drop_table('ojt_attendance')
    op.drop_table('site_settings')
    op.drop_table('partner')
    # ### end Alembic commands ###
