"""Add image_scale to Staff for photo zoom adjustment

Revision ID: 7304a2722d75
Revises: f7ddf44c033d
Create Date: 2026-06-30 11:54:33.164285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7304a2722d75'
down_revision = 'f7ddf44c033d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_scale', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('image_scale')

    # ### end Alembic commands ###
