"""Add sr_code to OJT

Revision ID: 7f44143aa33f
Revises: de6b3e2ae0c9
Create Date: 2026-07-22 14:31:52.785345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f44143aa33f'
down_revision = 'de6b3e2ae0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ojt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sr_code', sa.String(length=10), nullable=True))

    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_column('embed_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embed_url', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('ojt', schema=None) as batch_op:
        batch_op.drop_column('sr_code')

    # ### end Alembic commands ###
