"""Add page_type and embed_url to ResourcePage

Revision ID: 8ff7773c02fb
Revises: f19c5a7a54cf
Create Date: 2026-07-01 09:21:04.822858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff7773c02fb'
down_revision = 'f19c5a7a54cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('embed_url', sa.Text(), nullable=True))
        batch_op.drop_column('flipbook_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_page', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flipbook_link', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('embed_url')
        batch_op.drop_column('page_type')

    # ### end Alembic commands ###
