"""Add editable hero, research areas, about us lists, and vision/mission/values

Revision ID: aa527807c796
Revises: fecd15d18f87
Create Date: 2026-07-09 14:53:36.562796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa527807c796'
down_revision = 'fecd15d18f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon_key', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_offered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_eyebrow', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('hero_heading', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('hero_paragraph', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('about_paragraph', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vision', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mission', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quality_policy', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('quality_policy')
        batch_op.drop_column('mission')
        batch_op.drop_column('vision')
        batch_op.drop_column('about_paragraph')
        batch_op.drop_column('hero_paragraph')
        batch_op.drop_column('hero_heading')
        batch_op.drop_column('hero_eyebrow')

    op.drop_table('service_offered')
    op.drop_table('research_area')
    op.drop_table('equipment_item')
    op.drop_table('core_value')
    # ### end Alembic commands ###
