"""Add hero_image_url to site settings

Revision ID: de6b3e2ae0c9
Revises: aa527807c796
Create Date: 2026-07-09 15:41:08.471989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6b3e2ae0c9'
down_revision = 'aa527807c796'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hero_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_column('hero_image_url')

    # ### end Alembic commands ###
