"""Restructure LearningResource with ResourcePage children

Revision ID: f19c5a7a54cf
Revises: 451c8d2d38cd
Create Date: 2026-07-01 09:12:25.560267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f19c5a7a54cf'
down_revision = '451c8d2d38cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('flipbook_link', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['learning_resource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_resource', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    op.drop_table('resource_page')
    # ### end Alembic commands ###
