"""Add image_position to Staff for photo crop adjustment

Revision ID: f7ddf44c033d
Revises: 4f99053b8a08
Create Date: 2026-06-30 11:48:38.857958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ddf44c033d'
down_revision = '4f99053b8a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_position', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('image_position')

    # ### end Alembic commands ###
